### ISSUE TITLE
can't run Kafka producer (step 5)

### ISSUE THREAD

**Issue by jnm-ronquillo** [shayansm2/DE-zoomcamp-playground#2]
(base) ➜  DE-zoomcamp-playground git:(main) cd github-events-analyzer 
(base) ➜  github-events-analyzer git:(main) docker compose up -d
[+] Running 31/3
 ✔ elasticsearch 10 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                             43.9s 
 ✔ kibana 12 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                 100.8s 
 ✔ redpanda-console 6 layers [⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                               41.2s 
[+] Running 6/6
 ✔ Network github-events-analyzer_default  Crea...                                          0.1s 
 ✔ Network github-events-analyzer_elastic  Crea...                                          0.0s 
 ✔ Container elasticsearch                 Started                                          0.7s 
 ✔ Container redpanda-node                 Started                                          0.7s 
 ✔ Container kibana                        Started                                          0.7s 
 ✔ Container redpanda-console-panel        Started                                          0.2s 
(base) ➜  github-events-analyzer git:(main) cd src/main/java/org/example/
(base) ➜  example git:(main) javac GitHubEventsKafkaPublisher.java
GitHubEventsKafkaPublisher.java:3: error: package org.apache.kafka.clients.producer does not exist
import org.apache.kafka.clients.producer.KafkaProducer;
                                        ^
GitHubEventsKafkaPublisher.java:4: error: package org.apache.kafka.clients.producer does not exist
import org.apache.kafka.clients.producer.ProducerConfig;
                                        ^
GitHubEventsKafkaPublisher.java:5: error: package org.apache.kafka.clients.producer does not exist
import org.apache.kafka.clients.producer.ProducerRecord;
                                        ^
GitHubEventsKafkaPublisher.java:6: error: package org.apache.kafka.common.serialization does not exist
import org.apache.kafka.common.serialization.StringSerializer;
                                            ^
GitHubEventsKafkaPublisher.java:24: error: cannot find symbol
        KafkaProducer<String, String> producer = new KafkaProducer<>(getProperties());
        ^
  symbol:   class KafkaProducer
  location: class GitHubEventsKafkaPublisher
GitHubEventsKafkaPublisher.java:24: error: cannot find symbol
        KafkaProducer<String, String> producer = new KafkaProducer<>(getProperties());
                                                     ^
  symbol:   class KafkaProducer
  location: class GitHubEventsKafkaPublisher
GitHubEventsKafkaPublisher.java:29: error: cannot find symbol
            ProducerRecord<String, String> record = new ProducerRecord<>(Configs.KAFKA_TOPIC_NAME, line);
            ^
  symbol:   class ProducerRecord
  location: class GitHubEventsKafkaPublisher
GitHubEventsKafkaPublisher.java:29: error: cannot find symbol
            ProducerRecord<String, String> record = new ProducerRecord<>(Configs.KAFKA_TOPIC_NAME, line);
                                                        ^
  symbol:   class ProducerRecord
  location: class GitHubEventsKafkaPublisher
GitHubEventsKafkaPublisher.java:29: error: cannot find symbol
            ProducerRecord<String, String> record = new ProducerRecord<>(Configs.KAFKA_TOPIC_NAME, line);
                                                                         ^
  symbol:   variable Configs
  location: class GitHubEventsKafkaPublisher
GitHubEventsKafkaPublisher.java:47: error: cannot find symbol
        String filePath = GithubArchiveUtils.getGitHubArchiveFile(year, month, day, hour);
                          ^
  symbol:   variable GithubArchiveUtils
  location: class GitHubEventsKafkaPublisher
GitHubEventsKafkaPublisher.java:55: error: cannot find symbol
        properties.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, Configs.KAFKA_BOOTSTRAP_SERVER);
                               ^
  symbol:   variable ProducerConfig
  location: class GitHubEventsKafkaPublisher
GitHubEventsKafkaPublisher.java:55: error: cannot find symbol
        properties.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, Configs.KAFKA_BOOTSTRAP_SERVER);
                                                                        ^
  symbol:   variable Configs
  location: class GitHubEventsKafkaPublisher
GitHubEventsKafkaPublisher.java:56: error: cannot find symbol
        properties.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
                               ^
  symbol:   variable ProducerConfig
  location: class GitHubEventsKafkaPublisher
GitHubEventsKafkaPublisher.java:56: error: cannot find symbol
        properties.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
                                                                           ^
  symbol:   class StringSerializer
  location: class GitHubEventsKafkaPublisher
GitHubEventsKafkaPublisher.java:57: error: cannot find symbol
        properties.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
                               ^
  symbol:   variable ProducerConfig
  location: class GitHubEventsKafkaPublisher
GitHubEventsKafkaPublisher.java:57: error: cannot find symbol
        properties.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
                                                                             ^
  symbol:   class StringSerializer
  location: class GitHubEventsKafkaPublisher
16 errors

**Comment by shayansm2** [comment]
@jnm-ronquillo sorry that I forgot to mention in the readme file that you have to install maven and all it's dependencies (from `pom.xml` file) in order to run the java files.

Install Maven: Before you can use Maven, you need to install it on your system. You can download the latest version of Maven from the official website (https://maven.apache.org/download.cgi). Follow the installation instructions for your operating system.

Install the dependencies: Once you have added the dependencies to the pom.xml file, you can install them by running the following command in the terminal:
```
mvn clean install
```

This command will download the dependencies from the Maven repository and add them to your local Maven repository.
